### ISSUE TITLE
Non-english links and images are broken

### ISSUE THREAD

**Issue by asakura42** [eafer/rdrview#23]
Try it yourself:

`rdrview "https://en.wikipedia.org/wiki/Wikipedia"` and `rdrview "https://ja.wikipedia.org/wiki/ウィキペディア"`. In first case you can see images and go through links. But in second case all links became "file:///..." so you can't open them or watch images. 

I don't know what exactly this problem is, so sorry for possible mistake in the title.

**Comment by eafer** [comment]
The problem here is that

`https://ja.wikipedia.org/wiki/ウィキペディア`

is not actually a valid url, and libxml2 rejects it. If you copy-paste the wikipedia url from the address bar, or from an actual link inside the browser, you can see the real url, which is

`https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2`

I just pushed a somewhat hacky solution to get this to work, let me know if it helps.

**Comment by asakura42** [comment]
Nice! It works!
